### ISSUE TITLE
Open Source License for this project?

### ISSUE THREAD

**Issue by rkosinski941** [stevenvong/ares-webos-sdk#5]
Hi,

I noticed there is no open source license associated with this project.  Is it free for commercial use?

Thanks,

**Comment by stevenvong** [comment]
This repository appears to be misleading in terms of ownership, which I don't own the code. This is intended for myself to make use of distributed code with few modification for my own use.

Please refer to for the original distribution.
http://webostv.developer.lge.com/index.php?cID=2863
